// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Addresses          string
	Attachments        string
	CartItems          string
	Categories         string
	Deliveries         string
	OrderItems         string
	Orders             string
	ProductDetails     string
	Products           string
	ProductsReports    string
	Questions          string
	QuestionsReports   string
	QuestionsResponses string
	Reviews            string
	ReviewsReports     string
	ReviewsResponses   string
	ShippingRate       string
	TaxRates           string
	Transactions       string
	Users              string
	WishlistItems      string
}{
	Addresses:          "addresses",
	Attachments:        "attachments",
	CartItems:          "cart_items",
	Categories:         "categories",
	Deliveries:         "deliveries",
	OrderItems:         "order_items",
	Orders:             "orders",
	ProductDetails:     "product_details",
	Products:           "products",
	ProductsReports:    "products_reports",
	Questions:          "questions",
	QuestionsReports:   "questions_reports",
	QuestionsResponses: "questions_responses",
	Reviews:            "reviews",
	ReviewsReports:     "reviews_reports",
	ReviewsResponses:   "reviews_responses",
	ShippingRate:       "shipping_rate",
	TaxRates:           "tax_rates",
	Transactions:       "transactions",
	Users:              "users",
	WishlistItems:      "wishlist_items",
}
