openapi: 3.0.0
info:
  title: Auth service
  version: 0.0.0
tags: []
paths:
  /api/auth/recover_password:
    post:
      operationId: recoverPassword
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                passRecoverRequest:
                  $ref: '#/components/schemas/PassRecoverRequest'
              required:
                - passRecoverRequest
  /api/auth/sign_in:
    post:
      operationId: signIn
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signInReq:
                  $ref: '#/components/schemas/SignInRequest'
              required:
                - signInReq
  /api/auth/sign_out:
    get:
      operationId: signOut
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /api/auth/sign_up:
    post:
      operationId: signUp
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestError'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signUpReq:
                  $ref: '#/components/schemas/SignUpRequest'
              required:
                - signUpReq
components:
  schemas:
    AuthResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    InternalServerError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
          enum:
            - 500
        message:
          type: string
          enum:
            - Something went wrong. Try again later
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    InvalidRequestError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
          enum:
            - 400
        message:
          type: string
          enum:
            - Invalid Request
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    NotFoundError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
          enum:
            - 404
        message:
          type: string
          enum:
            - Not Found
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
    PassRecoverRequest:
      type: object
      required:
        - userNameOrEmail
      properties:
        userNameOrEmail:
          type: string
    SignInRequest:
      type: object
      required:
        - userNameOrEmail
        - password
      properties:
        userNameOrEmail:
          type: string
        password:
          type: string
    SignUpRequest:
      type: object
      required:
        - userName
        - fullName
        - email
        - phoneNumber
        - password
        - country
        - city
        - province
        - street
        - zipCode
      properties:
        userName:
          type: string
        fullName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        country:
          type: string
        city:
          type: string
        province:
          type: string
        street:
          type: string
        unitNumber:
          type: string
        zipCode:
          type: string
    UnauthorizedError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: number
          enum:
            - 401
        message:
          type: string
          enum:
            - Unauthorized
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
