# ../../typespec/tsp-output/@typespec/openapi3/openapi.ECommerce.SellerService.yaml
package: seller_server
generate:
  gin-server: true
  models: false
output: ./generated/oapi/seller_server/seller_server.go
