# ../../typespec/tsp-output/@typespec/openapi3/openapi.ECommerce.UsersService.yaml
package: users_server
generate:
  gin-server: true
  models: false
output: ./generated/oapi/users_server/users_server.go
